# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{activity_streams}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ruben Fonseca"]
  s.date = %q{2010-03-08}
  s.description = %q{Ruby module to eat and parse ActivityStreams in various formats}
  s.email = %q{root@cpan.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "activity_streams.gemspec",
     "lib/activity_streams.rb",
     "lib/activity_streams/common_fields.rb",
     "lib/activity_streams/feedzirra_patches.rb",
     "lib/activity_streams/portable_contact.rb",
     "spec/activity_streams_spec.rb",
     "spec/lastfm.xml",
     "spec/myspace.json",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/twitter.xml"
  ]
  s.homepage = %q{http://github.com/webcracy/activity_streams}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby module to eat and parse ActivityStreams in various formats}
  s.test_files = [
    "spec/activity_streams_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<sax-machine>, [">= 0.0.15"])
      s.add_runtime_dependency(%q<feedzirra>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<sax-machine>, [">= 0.0.15"])
      s.add_dependency(%q<feedzirra>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<sax-machine>, [">= 0.0.15"])
    s.add_dependency(%q<feedzirra>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 0"])
  end
end

